### PR TITLE
feat/staked-amount-monitor

### PR DESCRIPTION
**Pull request by sotnikov-s**
Added a new monitor and a corresponding panel panel that shows amount of staked Luna. It's configured to alert if the amount is greater than 300 millions which would mean that stake has grown significantly and there could be a malicious user.

Screen Shot 2022-05-11 at 21 20 17
Screen Shot 2022-05-11 at 21 19 47
Screen Shot 2022-05-11 at 21 19 59

### CODE REVIEW

**Review by oopcode — APPROVED** [review]

**Comment by sotnikov-s** [comment]
increased the sane staked luna amount to 600m

**Comment by sotnikov-s** [comment]
increased the sane staked luna amount to 800m

**Comment by swelf19** [comment]
what do you think about to implement step based alerts similar to missed blocks alerts?

**Review by pr0n00gler — APPROVED** [review]

**Comment by sotnikov-s** [comment]
> what do you think about to implement step based alerts similar to missed blocks alerts?

we thought about it with @turinkay and came to conclusion that
1. it's less reliable
2. it's not quite clear what would be the steps in terms of staked luna amount

so we decided just to use that blunt alert rule

**Pull request merged**
